### ISSUE TITLE
关于板载多个W5500

### ISSUE THREAD

**Issue by ke00001** [Ryan-CW-Code/RyanW5500#1]
请问关于板载多个w5500有没有建议，RyanW5500的会不会增加多个w5500支持。

**Comment by Ryan-CW-Code** [comment]
不能哦，虽然最初设想的是可以挂载多个。
但由于使用了wiz-chip作为底层库，修改起来工作量有些大（重复工作太多）。
有兴趣的话你可以尝试一下
有多个以太网芯片需求的还是建议使用软件tcp/ip协议栈啦
