### ISSUE TITLE
当前软件包不存在于rt-thread资源索引中

### ISSUE THREAD

**Issue by CsyBarry** [Ryan-CW-Code/RyanW5500#2]
无法在rt-thread 中安装该软件包，提示当前软件包不存在于rt-thread资源索引中，按要求更新软件包没有效果

**Comment by Ryan-CW-Code** [comment]
env使用 pkgs --update 命令更新软件包列表（RT-Thread Studio 2.2.6版本已经可以右击项目打开env 终端）
使用 pkgs <search|info> pkg-name 命令搜索软件包并查看软件包信息?

尝试删除软件包索引，再执行更新命令
