### ISSUE TITLE
rt-thread 的 sal_check_netdev_internet_up 通不过

### ISSUE THREAD

**Issue by shishirong** [Ryan-CW-Code/RyanW5500#3]
应用程序是通过NETDEV_FLAG_INTERNET_UP检查联网状态的,sal_check_netdev_internet_up 执行总是失败.

此外还遇到的问题:
1.   RyanW5500CreateListenClient函数中调用 RyanW5500CheckCode宏会报错(编译器版本mdk5 AC6), 因为函数返回值类型是RyanW5500Socket *,宏展开后 return ErrorCode, 类型不对.

**Comment by Ryan-CW-Code** [comment]
sal_check_netdev_internet_up 函数连接rtt服务器进行网络检查的。   你可以自己使用 ping www.baidu.com 来判断是否联网成功
我用的gcc编译器没有报错，mdk不智能呀。   可以使用 RyanW5500CheckCodeNoReturn 宏来替代

**Comment by Ryan-CW-Code** [comment]
刚推了个更新，使用 RyanW5500CheckCodeNoReturn 代替部分函数的 RyanW5500CheckCode。
但是这个没有经过测试（这两天考试，没时间测试），你可以先试一下，有问题再联系
